// Project starter templates seeded by /api/projects/create-with-github when
// the user picks one. Each template is a small set of files that get committed
// to the brand-new repo in one Git Tree API call (single round-trip).
//
// Why inline files rather than a GitHub template-repo?
//   1. No external repo to maintain. Add a starter by editing this file.
//   2. Templates can include the user's chosen project name via {{NAME}}
//      placeholders — we substitute server-side before commit.
//   3. Single API call vs. forking + maintaining a template-repo on GitHub.
//
// Adding a starter: append a new TEMPLATES entry with its file map. Keep each
// starter small (< 15 files) so the commit stays under GitHub's tree-size
// limits and the choice list stays scannable.

import { APP_URL } from "@/config/brand";
import { PROVISION_TEMPLATES, type ProvisionTemplateId } from "@/config/project-templates";

/** Ids + labels come from the light config so pickers can import them without
 *  pulling every starter's file bodies into their bundle. */
export type TemplateId = ProvisionTemplateId;

export interface TemplateMeta {
  id: TemplateId;
  label: string;
  description: string;
  /** Map of repo-relative path → file contents. {{NAME}} is replaced with
   *  the slugged repo name; {{DESCRIPTION}} with the project description. */
  files: Record<string, string>;
  /** Human-readable infra the first agent task will set up on the user's
   *  machine — shown on the post-create bridge so the user sees what gets
   *  handled automatically (deps, database, dev server) vs. left to them. */
  infra: string[];
  /** The pre-composed first dispatch: an agent runs this to take the freshly
   *  cloned repo from "files exist" to "running locally", setting up everything
   *  the stack needs (dependencies, database + schema, dev server) — the
   *  auto-infra step, done where the code actually runs. {{NAME}} substituted. */
  firstTask: string;
}

const NEXTJS_PAGE_TSX = `export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-8">
      <div className="max-w-2xl text-center space-y-4">
        <h1 className="text-4xl font-bold tracking-tight">{{NAME}}</h1>
        <p className="text-lg text-gray-600 dark:text-gray-400">
          {{DESCRIPTION}}
        </p>
        <p className="text-sm text-gray-500 mt-8">
          Edit <code className="px-2 py-0.5 rounded bg-gray-100 dark:bg-gray-800 font-mono text-xs">src/app/page.tsx</code> to get started.
        </p>
      </div>
    </main>
  );
}
`;

const NEXTJS_LAYOUT_TSX = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "{{NAME}}",
  description: "{{DESCRIPTION}}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`;

const NEXTJS_GLOBALS_CSS = `@import "tailwindcss";

@theme {
  --font-sans: ui-sans-serif, system-ui, -apple-system, sans-serif;
}

:root {
  color-scheme: light dark;
}
`;

const NEXTJS_PACKAGE_JSON = `{
  "name": "{{NAME}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4.0.0",
    "@tailwindcss/postcss": "^4.0.0",
    "typescript": "^5"
  }
}
`;

const NEXTJS_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const NEXTJS_NEXT_CONFIG = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Add your config here. See https://nextjs.org/docs/app/api-reference/next-config-js
};

export default nextConfig;
`;

const NEXTJS_POSTCSS = `module.exports = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;

const NEXTJS_GITIGNORE = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files
.env*.local
.env

# typescript
*.tsbuildinfo
next-env.d.ts
`;

const NEXTJS_README = `# {{NAME}}

{{DESCRIPTION}}

> Generated by [FleetCrown](${APP_URL}/) — the captain-mode command center for your AI agent fleet.

## Stack

- [Next.js 15](https://nextjs.org) (App Router, Server Components)
- [Tailwind CSS v4](https://tailwindcss.com)
- TypeScript

## Get started

\`\`\`bash
git clone <this-repo-url>
cd {{NAME}}
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## What's here

\`\`\`
src/app/
├── layout.tsx     ← root layout
├── page.tsx       ← home page
└── globals.css    ← Tailwind v4 import + theme tokens
\`\`\`

Edit \`src/app/page.tsx\` to make it yours. Tailwind classes work out of the box.

## What's next

- Add a database: \`npm install drizzle-orm postgres\` + see [Drizzle docs](https://orm.drizzle.team)
- Add auth: \`npm install next-auth@beta\` + see [Auth.js docs](https://authjs.dev)
- Deploy: self-host behind a reverse proxy (build, then run \`next start\` on your server)

## Need help?

Open this project in FleetCrown's Control panel to dispatch AI agents at it.
`;

// ── Python + FastAPI (uv) ────────────────────────────────────────────────

const FASTAPI_PYPROJECT = `[project]
name = "{{NAME}}"
version = "0.1.0"
description = "{{DESCRIPTION}}"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.32",
]

[dependency-groups]
dev = [
  "ruff>=0.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
`;

const FASTAPI_MAIN = `from fastapi import FastAPI

app = FastAPI(title="{{NAME}}", description="{{DESCRIPTION}}")


@app.get("/")
def root():
    return {"name": "{{NAME}}", "status": "ok"}


@app.get("/health")
def health():
    return {"ok": True}
`;

const FASTAPI_README = `# {{NAME}}

{{DESCRIPTION}}

> Generated by [FleetCrown](${APP_URL}/).

## Stack

- Python 3.11+
- [FastAPI](https://fastapi.tiangolo.com) (async web framework)
- [uv](https://docs.astral.sh/uv/) (fast Python package manager)

## Get started

\`\`\`bash
# Install uv if you don't have it:
curl -LsSf https://astral.sh/uv/install.sh | sh

# Then:
uv sync
uv run uvicorn src.main:app --reload
\`\`\`

Open [http://localhost:8000/docs](http://localhost:8000/docs) for the interactive API.

## What's here

\`\`\`
src/main.py     ← FastAPI app with GET / and GET /health
pyproject.toml  ← deps + project metadata
\`\`\`

## What's next

- Add a database: \`uv add sqlmodel asyncpg\` + see [SQLModel](https://sqlmodel.tiangolo.com)
- Add background jobs: \`uv add arq\` or \`uv add taskiq\`
- Deploy to Fly.io / Railway / Render — they all auto-detect FastAPI
`;

const FASTAPI_GITIGNORE = `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/
.eggs/

# uv / venv
.venv/
venv/
.uv-cache/

# environments
.env
.env.*

# IDE
.vscode/
.idea/

# OS
.DS_Store
`;

// ── Hono + Cloudflare Workers ────────────────────────────────────────────

const HONO_PACKAGE = `{
  "name": "{{NAME}}",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "wrangler dev",
    "deploy": "wrangler deploy"
  },
  "dependencies": {
    "hono": "^4.6.0"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240925.0",
    "typescript": "^5.6.0",
    "wrangler": "^4.0.0"
  }
}
`;

const HONO_INDEX = `import { Hono } from "hono";

type Bindings = {
  // Add Cloudflare bindings here (KV, D1, R2, env vars).
};

const app = new Hono<{ Bindings: Bindings }>();

app.get("/", (c) =>
  c.json({
    name: "{{NAME}}",
    description: "{{DESCRIPTION}}",
    status: "ok",
  }),
);

app.get("/health", (c) => c.json({ ok: true }));

export default app;
`;

const HONO_WRANGLER = `name = "{{NAME}}"
main = "src/index.ts"
compatibility_date = "2025-01-01"
`;

const HONO_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "lib": ["ES2022"],
    "types": ["@cloudflare/workers-types"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["src/**/*.ts"]
}
`;

const HONO_README = `# {{NAME}}

{{DESCRIPTION}}

> Generated by [FleetCrown](${APP_URL}/).

## Stack

- [Hono](https://hono.dev) (tiny, ultrafast web framework)
- [Cloudflare Workers](https://workers.cloudflare.com) (edge serverless, free tier 100k req/day)
- TypeScript

## Get started

\`\`\`bash
npm install
npx wrangler login          # one-time, opens browser
npm run dev                 # local Worker on http://localhost:8787
\`\`\`

When ready:

\`\`\`bash
npm run deploy              # ships to <your-account>.workers.dev
\`\`\`

## What's here

\`\`\`
src/index.ts     ← Hono app with GET / and GET /health
wrangler.toml    ← Cloudflare Worker config
\`\`\`

## What's next

- Add a database: \`npx wrangler d1 create my-db\` → bind in \`wrangler.toml\` → \`c.env.DB.prepare(...)\`
- Add KV storage: \`npx wrangler kv:namespace create CACHE\`
- Add R2 object storage for files

[Hono cookbook](https://hono.dev/docs/getting-started/cloudflare-workers)
`;

const HONO_GITIGNORE = `node_modules
.wrangler
dist
.dev.vars
.env*
*.log
.DS_Store
`;

// ── Plain HTML + Tailwind (CDN) ──────────────────────────────────────────

const HTML_INDEX = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{NAME}}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen flex items-center justify-center bg-gray-50">
  <div class="max-w-2xl text-center px-8 space-y-4">
    <h1 class="text-5xl font-bold tracking-tight text-gray-900">{{NAME}}</h1>
    <p class="text-lg text-gray-600">{{DESCRIPTION}}</p>
    <p class="text-sm text-gray-400 mt-8">
      Edit <code class="px-2 py-0.5 rounded bg-gray-100 font-mono text-xs">index.html</code> to get started.
    </p>
  </div>
  <script src="main.js"></script>
</body>
</html>
`;

const HTML_MAIN = `// Plain JS. No build step. Add interactivity here.
console.log("Hello from {{NAME}}");
`;

const HTML_README = `# {{NAME}}

{{DESCRIPTION}}

> Generated by [FleetCrown](${APP_URL}/).

## Stack

- Plain HTML, JS, and Tailwind via CDN. **No build step.** Open \`index.html\` in a browser and it works.

## Get started

\`\`\`bash
# macOS / Linux
open index.html

# OR serve it locally if you want hot-reload:
npx serve .
\`\`\`

## What's next

- Add more pages: just create \`about.html\`, link to it.
- Outgrow the CDN: install Tailwind properly with \`npm init -y && npm install -D tailwindcss\`
- Need a backend? Use the **Hono + Cloudflare Workers** FleetCrown template alongside this for the API.
`;

const HTML_GITIGNORE = `.DS_Store
node_modules
*.log
`;

// ── Registry ──────────────────────────────────────────────────────────────

/** What a starter actually seeds — the half too heavy for a picker to import. */
type TemplateBuild = Pick<TemplateMeta, "files" | "infra" | "firstTask">;

const TEMPLATE_BUILDS: Record<TemplateId, TemplateBuild> = {
  bare: {
    files: {}, // empty — the GitHub auto_init flag already creates README.md
    infra: ["Stack chosen to fit the goal", "Dependencies installed", "Dev server running"],
    firstTask:
      'This is a fresh empty repo for "{{NAME}}". Set it up from scratch: pick the simplest stack that fits the project goal, scaffold it, install dependencies, set up any database the project needs (a local Postgres or SQLite — your call, create a .env with the connection string and keep secrets out of git), and get a dev server running. Then tell me the stack you chose and the exact command + URL to run it.',
  },
  "nextjs-tailwind": {
    files: {
      "package.json": NEXTJS_PACKAGE_JSON,
      "tsconfig.json": NEXTJS_TSCONFIG,
      "next.config.ts": NEXTJS_NEXT_CONFIG,
      "postcss.config.js": NEXTJS_POSTCSS,
      ".gitignore": NEXTJS_GITIGNORE,
      "README.md": NEXTJS_README,
      "src/app/page.tsx": NEXTJS_PAGE_TSX,
      "src/app/layout.tsx": NEXTJS_LAYOUT_TSX,
      "src/app/globals.css": NEXTJS_GLOBALS_CSS,
    },
    infra: ["npm install", "Database (Postgres via Drizzle, or SQLite)", "Dev server on :3000"],
    firstTask:
      'Set up this Next.js 15 project "{{NAME}}" end to end so it runs locally: run `npm install`; if the project needs persistence, add a database (Drizzle ORM + a local Postgres, or SQLite for a quick start), define an initial schema and migration, and create a `.env.local` with the connection string (never commit it); then start the dev server with `npm run dev`. Confirm it builds and renders at http://localhost:3000, then summarize what you set up and how to run it.',
  },
  "python-fastapi": {
    files: {
      "pyproject.toml": FASTAPI_PYPROJECT,
      "src/main.py": FASTAPI_MAIN,
      "README.md": FASTAPI_README,
      ".gitignore": FASTAPI_GITIGNORE,
    },
    infra: ["uv sync", "Database (Postgres via SQLModel, or SQLite)", "Dev server on :8000"],
    firstTask:
      'Set up this FastAPI project "{{NAME}}" so it runs locally: run `uv sync`; if it needs persistence, add a database layer (SQLModel + a local Postgres via asyncpg, or SQLite to start), wire an initial model + migration, and put the connection string in a `.env` (keep it out of git); then start the server with `uv run uvicorn src.main:app --reload`. Confirm http://localhost:8000/health and /docs respond, then summarize what you set up.',
  },
  "hono-cloudflare": {
    files: {
      "package.json": HONO_PACKAGE,
      "wrangler.toml": HONO_WRANGLER,
      "tsconfig.json": HONO_TSCONFIG,
      "src/index.ts": HONO_INDEX,
      "README.md": HONO_README,
      ".gitignore": HONO_GITIGNORE,
    },
    infra: ["npm install", "D1 database binding (if needed)", "Local Worker on :8787"],
    firstTask:
      'Set up this Hono + Cloudflare Workers project "{{NAME}}" so it runs locally: run `npm install`; if it needs persistence, create a D1 database (`npx wrangler d1 create`), bind it in `wrangler.toml`, and add a first table/migration; then run `npm run dev`. Confirm http://localhost:8787 responds, then summarize what you set up and the deploy command.',
  },
  "html-tailwind": {
    files: {
      "index.html": HTML_INDEX,
      "main.js": HTML_MAIN,
      "README.md": HTML_README,
      ".gitignore": HTML_GITIGNORE,
    },
    infra: ["Local static server"],
    firstTask:
      'Serve this static site "{{NAME}}" locally (`npx serve .`) and confirm it renders in a browser. No database is needed yet — if the project later needs a backend, say so and recommend the Hono + Cloudflare Workers stack alongside it. Summarize how to run it.',
  },
};

/** The full registry: light metadata (config) + what it seeds (above). */
export const TEMPLATES: Record<TemplateId, TemplateMeta> = Object.fromEntries(
  PROVISION_TEMPLATES.map((template) => [
    template.id,
    {
      id: template.id,
      label: template.label,
      description: template.description,
      ...TEMPLATE_BUILDS[template.id],
    },
  ]),
) as Record<TemplateId, TemplateMeta>;

/**
 * Substitute {{NAME}} / {{DESCRIPTION}} placeholders in a file body.
 * Kept tiny — no real templating engine. If we add more placeholders or
 * conditional blocks, lift to a proper templating step.
 */
export function renderTemplate(
  content: string,
  values: { name: string; description: string },
): string {
  return content
    .replaceAll("{{NAME}}", values.name)
    .replaceAll("{{DESCRIPTION}}", values.description);
}
