// Project starter templates seeded by /api/projects/create-with-github when
// the user picks one. Each template is a small set of files that get committed
// to the brand-new repo in one Git Tree API call (single round-trip).
//
// Why inline files rather than a GitHub template-repo?
//   1. No external repo to maintain. Add a starter by editing this file.
//   2. Templates can include the user's chosen project name via {{NAME}}
//      placeholders — we substitute server-side before commit.
//   3. Single API call vs. forking + maintaining a template-repo on GitHub.
//
// Adding a starter: append a new TEMPLATES entry with its file map. Keep each
// starter small (< 15 files) so the commit stays under GitHub's tree-size
// limits and the choice list stays scannable.

export type TemplateId = "bare" | "nextjs-tailwind";

export interface TemplateMeta {
  id: TemplateId;
  label: string;
  description: string;
  /** Map of repo-relative path → file contents. {{NAME}} is replaced with
   *  the slugged repo name; {{DESCRIPTION}} with the project description. */
  files: Record<string, string>;
}

const NEXTJS_PAGE_TSX = `export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-8">
      <div className="max-w-2xl text-center space-y-4">
        <h1 className="text-4xl font-bold tracking-tight">{{NAME}}</h1>
        <p className="text-lg text-gray-600 dark:text-gray-400">
          {{DESCRIPTION}}
        </p>
        <p className="text-sm text-gray-500 mt-8">
          Edit <code className="px-2 py-0.5 rounded bg-gray-100 dark:bg-gray-800 font-mono text-xs">src/app/page.tsx</code> to get started.
        </p>
      </div>
    </main>
  );
}
`;

const NEXTJS_LAYOUT_TSX = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "{{NAME}}",
  description: "{{DESCRIPTION}}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`;

const NEXTJS_GLOBALS_CSS = `@import "tailwindcss";

@theme {
  --font-sans: ui-sans-serif, system-ui, -apple-system, sans-serif;
}

:root {
  color-scheme: light dark;
}
`;

const NEXTJS_PACKAGE_JSON = `{
  "name": "{{NAME}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "tailwindcss": "^4.0.0",
    "@tailwindcss/postcss": "^4.0.0",
    "typescript": "^5"
  }
}
`;

const NEXTJS_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const NEXTJS_NEXT_CONFIG = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Add your config here. See https://nextjs.org/docs/app/api-reference/next-config-js
};

export default nextConfig;
`;

const NEXTJS_POSTCSS = `module.exports = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;

const NEXTJS_GITIGNORE = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files
.env*.local
.env

# typescript
*.tsbuildinfo
next-env.d.ts

# vercel
.vercel
`;

const NEXTJS_README = `# {{NAME}}

{{DESCRIPTION}}

> Generated by [FleetCrown](https://fleetcrown.vercel.app/) — the captain-mode command center for your AI agent fleet.

## Stack

- [Next.js 15](https://nextjs.org) (App Router, Server Components)
- [Tailwind CSS v4](https://tailwindcss.com)
- TypeScript

## Get started

\`\`\`bash
git clone <this-repo-url>
cd {{NAME}}
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## What's here

\`\`\`
src/app/
├── layout.tsx     ← root layout
├── page.tsx       ← home page
└── globals.css    ← Tailwind v4 import + theme tokens
\`\`\`

Edit \`src/app/page.tsx\` to make it yours. Tailwind classes work out of the box.

## What's next

- Add a database: \`npm install drizzle-orm postgres\` + see [Drizzle docs](https://orm.drizzle.team)
- Add auth: \`npm install next-auth@beta\` + see [Auth.js docs](https://authjs.dev)
- Deploy to Vercel: \`npx vercel\`

## Need help?

Open this project in FleetCrown's Control panel to dispatch AI agents at it.
`;

export const TEMPLATES: Record<TemplateId, TemplateMeta> = {
  bare: {
    id: "bare",
    label: "Empty (just a README)",
    description: "Just a README. Bring your own stack.",
    files: {}, // empty — the GitHub auto_init flag already creates README.md
  },
  "nextjs-tailwind": {
    id: "nextjs-tailwind",
    label: "Next.js 15 + Tailwind v4",
    description: "App Router, TypeScript, Tailwind CSS v4. `npm install && npm run dev` and you're live.",
    files: {
      "package.json": NEXTJS_PACKAGE_JSON,
      "tsconfig.json": NEXTJS_TSCONFIG,
      "next.config.ts": NEXTJS_NEXT_CONFIG,
      "postcss.config.js": NEXTJS_POSTCSS,
      ".gitignore": NEXTJS_GITIGNORE,
      "README.md": NEXTJS_README,
      "src/app/page.tsx": NEXTJS_PAGE_TSX,
      "src/app/layout.tsx": NEXTJS_LAYOUT_TSX,
      "src/app/globals.css": NEXTJS_GLOBALS_CSS,
    },
  },
};

/**
 * Substitute {{NAME}} / {{DESCRIPTION}} placeholders in a file body.
 * Kept tiny — no real templating engine. If we add more placeholders or
 * conditional blocks, lift to a proper templating step.
 */
export function renderTemplate(
  content: string,
  values: { name: string; description: string },
): string {
  return content
    .replaceAll("{{NAME}}", values.name)
    .replaceAll("{{DESCRIPTION}}", values.description);
}
