// GENERATED by scripts/generate-widget-theme.ts from @bitbaum/design-tokens@1.1.0
// — do not edit; change the tokens and regenerate. scripts/test/widget-theme-from-tokens.ts
// fails when this file is stale.
export const WIDGET_THEME = {
  accent: "#ff5c00",
  accentHover: "#ff7a33",
  accentMuted: "rgba(255,92,0,0.16)",
  inkOnAccent: "#141414",
  text: "#ebebeb",
  textSecondary: "#a6a6a6",
  textTertiary: "#7a7a7a",
  textMuted: "#525252",
  surface: "#0a0a0a",
  surfaceRaised: "#121212",
  surfaceSubtle: "#212121",
  border: "#212121",
  borderStrong: "#333333",
  borderDark: "#3d3d3d",
  success: "#39c674",
  error: "#e64c4c",
  errorSurface: "rgba(230,76,76,0.12)",
  black: "#0a0a0a",
  white: "#ffffff",
  radiusControl: "6px",
  radiusSurface: "8px",
  fontSans: "'Inter', system-ui, -apple-system, sans-serif",
  fontMono: "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
} as const;

export type WidgetThemeShape = typeof WIDGET_THEME;
