// Regenerate the pnpm lockfile shipped inside the nextjs-tailwind starter.
//
// Why a lockfile is part of the starter at all: selfhost-deploy.yml refuses to
// install without one ("no lockfile at the repo root — cannot install
// reproducibly"), and it installs with --frozen-lockfile. A starter that
// declares pnpm but ships no lock therefore cannot deploy on its first push —
// which is exactly the cold-start bar (brief → repo → live site) this starter
// exists for. Generating the lock at provision time would need pnpm + network
// on the app box for every kickoff; resolving it once here and committing the
// result keeps provisioning a pure GitHub API call.
//
// Run after changing the starter's package.json:
//   pnpm exec tsx scripts/templates/refresh-starter-lock.ts
// scripts/test/starter-lock.ts fails when the two drift.
import { execFileSync } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import { fileURLToPath } from "url";
import { renderTemplate, TEMPLATES } from "@/lib/project-templates";
import { STARTER_LOCK_FILE, STARTER_LOCK_TEMPLATE } from "@/lib/starter-locks/config";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "../../src/lib/starter-locks", `${STARTER_LOCK_TEMPLATE}.generated.ts`);

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "fc-starter-lock-"));
try {
  const files = TEMPLATES[STARTER_LOCK_TEMPLATE].files;
  for (const [rel, body] of Object.entries(files)) {
    if (rel === STARTER_LOCK_FILE) continue;
    const dest = path.join(tmp, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, renderTemplate(body, { name: "starter", description: "starter" }));
  }
  execFileSync("pnpm", ["install", "--lockfile-only", "--ignore-scripts"], {
    cwd: tmp,
    stdio: "inherit",
  });
  const lock = fs.readFileSync(path.join(tmp, STARTER_LOCK_FILE), "utf8");
  const escaped = lock.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  const banner = [
    "// GENERATED by scripts/templates/refresh-starter-lock.ts — do not edit by hand.",
    `// The ${STARTER_LOCK_TEMPLATE} starter's package.json, resolved once with`,
    "// `pnpm install --lockfile-only`. selfhost-deploy installs starters with",
    "// --frozen-lockfile, so this must match that package.json exactly;",
    "// scripts/test/starter-lock.ts enforces it.",
    "",
  ].join("\n");
  fs.writeFileSync(OUT, `${banner}export const NEXTJS_TAILWIND_PNPM_LOCK = \`${escaped}\`;\n`);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (${lock.split("\n").length} lines)`);
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
