// The self-improvement half of the frontier loop.
//
// Given a day's digest, draft concrete proposals for how FleetCrown itself
// should evolve, then put them through an adversarial self-critique gate before
// any reach a human. The loop AUTO-PROPOSES ONLY — a human accepts (→ a roadmap
// goal) or dismisses. Decision history grounds the next run so nothing is
// re-proposed.
//
// On model-agnosticism: proposals are generated by the GENERATOR model (Meta
// llama-3.3) and judged by a PANEL of different model lineages (verifyProposals).
// A single same-model judge shares the generator's blind spots — it certifies
// its own bad patterns. Judges from different training lineages have
// uncorrelated errors, so a proposal must convince every diverse judge that
// votes. That is what makes the judge strictly harder to fool than the
// generator — the whole point of the loop.

import { callGroqText } from "@/lib/groq";
import type { FrontierItem } from "./types";

// Short, stable grounding so proposals stay on-target for what FleetCrown is.
const FLEETCROWN_MISSION = `FleetCrown is a multi-user SaaS platform for commanding AI agent fleets across projects: builders register projects and launch/monitor/govern vendor-agnostic AI agents (claude, cursor, codex, gemini, grok) from one control plane. It is model-agnostic, self-hosted, and its north star is captain-mode: see and govern across the agents you've deployed. A local "Fleet Runner" desktop executes dispatches; the cloud orchestrates.`;

export type DraftProposal = { title: string; rationale: string; sourceUrls: string[] };

export type ProposalContext = {
  /** Titles of the owner's current active goals — do not duplicate. */
  activeGoalTitles: string[];
  /** Titles already proposed/considered (incl. dismissed) — do not repropose. */
  consideredTitles: string[];
};

function digestForPrompt(items: FrontierItem[]): string {
  return items.map((it, i) => `[${i}] (${it.category}) ${it.title} — ${it.summary} <${it.url}>`).join("\n");
}

const GENERATE_SYSTEM = `You are FleetCrown's self-improvement strategist.

${FLEETCROWN_MISSION}

Given today's frontier developments AND FleetCrown's current goals, propose AT MOST 3 specific, actionable ways FleetCrown should evolve. Each proposal MUST:
- tie a specific frontier development to a specific FleetCrown capability (not generic "use more AI");
- be concrete enough that an engineer could start building it;
- NOT duplicate an existing active goal or a previously-considered proposal.

If nothing today genuinely warrants a new direction, return an empty list. Do NOT invent work to fill the quota — an empty list is the correct answer most days.

Return STRICT JSON only:
{"proposals":[{"title":"...","rationale":"... (2-3 sentences, name the frontier item and the FleetCrown capability)","sourceUrls":["<url from the candidate list>"]}]}`;

const CRITIQUE_SYSTEM = `You are an adversarial reviewer of self-improvement proposals for FleetCrown (a model-agnostic AI-agent-fleet control plane). Default to REJECTING. A proposal only earns a high score if it is ALL of: genuinely actionable, specific to FleetCrown (not generic AI hype), tied to a real frontier development, and NOT a restatement of an existing goal.

Score each proposal 0-100. Be harsh: vague, derivative, or me-too proposals score below 50. Only proposals a thoughtful founder would actually add to the roadmap score 70+.

Return STRICT JSON only: {"scores":[{"index":<number>,"score":<0-100>}]}`;

// Reasoning models (e.g. qwen3) emit a <think>…</think> preamble before the
// answer — drop it so the JSON after it parses, and so stray braces inside the
// reasoning don't get mistaken for the payload.
function stripReasoning(text: string): string {
  const idx = text.lastIndexOf("</think>");
  return idx === -1 ? text : text.slice(idx + "</think>".length);
}

// Pull the first balanced {...} object out of a (possibly fenced) model reply.
function extractJson(raw: string): string | null {
  const text = stripReasoning(raw);
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const body = fenced ? fenced[1] : text;
  const start = body.indexOf("{");
  if (start === -1) return null;
  let depth = 0;
  for (let i = start; i < body.length; i++) {
    if (body[i] === "{") depth++;
    else if (body[i] === "}" && --depth === 0) return body.slice(start, i + 1);
  }
  return null;
}

function safeParse<T>(text: string): T | null {
  const json = extractJson(text);
  if (!json) return null;
  try { return JSON.parse(json) as T; } catch { return null; }
}

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim();
}

// Word-overlap (Jaccard) — a cheap code-level dedup net beyond the LLM's own
// instruction not to duplicate.
function tooSimilar(a: string, b: string): boolean {
  const wa = new Set(norm(a).split(" ").filter((w) => w.length > 3));
  const wb = new Set(norm(b).split(" ").filter((w) => w.length > 3));
  if (wa.size === 0 || wb.size === 0) return false;
  let inter = 0;
  for (const w of wa) if (wb.has(w)) inter++;
  const union = wa.size + wb.size - inter;
  return inter / union >= 0.6;
}

export async function generateProposals(
  items: FrontierItem[],
  ctx: ProposalContext,
): Promise<DraftProposal[]> {
  if (items.length === 0) return [];
  const validUrls = new Set(items.map((it) => it.url));

  const user = [
    `Today's frontier digest:\n${digestForPrompt(items)}`,
    ctx.activeGoalTitles.length ? `\nCurrent active goals (do NOT duplicate):\n- ${ctx.activeGoalTitles.join("\n- ")}` : "",
    ctx.consideredTitles.length ? `\nAlready considered (do NOT repropose):\n- ${ctx.consideredTitles.join("\n- ")}` : "",
  ].join("\n");

  let raw: string;
  try {
    raw = await callGroqText(user, { systemPrompt: GENERATE_SYSTEM, maxTokens: 1100, temperature: 0.4, timeoutMs: 22_000 });
  } catch {
    return [];
  }

  const parsed = safeParse<{ proposals?: unknown }>(raw);
  const list = Array.isArray(parsed?.proposals) ? parsed!.proposals : [];
  const drafts: DraftProposal[] = [];
  for (const p of list) {
    if (typeof p !== "object" || !p) continue;
    const title = String((p as Record<string, unknown>).title ?? "").trim();
    const rationale = String((p as Record<string, unknown>).rationale ?? "").trim();
    const urlsRaw = (p as Record<string, unknown>).sourceUrls;
    const sourceUrls = Array.isArray(urlsRaw) ? urlsRaw.map(String).filter((u) => validUrls.has(u)) : [];
    if (!title || !rationale) continue;
    // Code-level dedup against goals + already-considered + earlier drafts this run.
    if ([...ctx.activeGoalTitles, ...ctx.consideredTitles, ...drafts.map((d) => d.title)].some((t) => tooSimilar(t, title))) continue;
    drafts.push({ title, rationale, sourceUrls });
    if (drafts.length >= 3) break;
  }
  return drafts;
}

// The judge panel — model lineages DIFFERENT from the generator (Meta llama-3.3)
// so their errors are uncorrelated with it and each other. Reasoning models get
// token headroom for their <think> preamble (stripped before parsing).
export type Judge = { model: string; maxTokens: number };
export const VERIFIER_PANEL: Judge[] = [
  { model: "openai/gpt-oss-120b", maxTokens: 600 },  // OpenAI lineage
  { model: "qwen/qwen3.6-27b",    maxTokens: 3500 }, // Qwen / Alibaba lineage (reasoning — needs room for <think>)
];

/** A proposal surfaces only if the panel's MEAN score clears this bar… */
export const PROPOSAL_SCORE_THRESHOLD = 70;
/** …AND no single judge scores below this (one diverse judge can veto, so a
 *  proposal one lineage loves and another hates never slips through). */
export const PROPOSAL_VETO_FLOOR = 50;

export type VerifierScore = { model: string; score: number };
export type VerifiedProposal = DraftProposal & {
  score: number;               // consensus = lowest panel score (conservative)
  passed: boolean;             // every voting judge >= threshold (>=1 voter)
  verifierScores: VerifierScore[];
};

function shortModel(id: string): string {
  return id.includes("/") ? id.split("/")[1] : id;
}

// One judge scores every draft in a single call → Map<draftIndex, score>.
// A judge that errors or returns junk abstains (empty map) rather than blocking.
async function runJudge(drafts: DraftProposal[], judge: Judge): Promise<Map<number, number>> {
  const user = `Proposals to review:\n${drafts.map((d, i) => `[${i}] ${d.title} — ${d.rationale}`).join("\n")}`;
  const byIndex = new Map<number, number>();
  let raw: string;
  try {
    raw = await callGroqText(user, {
      systemPrompt: CRITIQUE_SYSTEM,
      maxTokens: judge.maxTokens,
      temperature: 0.1,
      timeoutMs: 35_000, // reasoning judges (qwen <think>) need headroom
      model: judge.model,
    });
  } catch {
    return byIndex;
  }
  const parsed = safeParse<{ scores?: Array<{ index?: unknown; score?: unknown }> }>(raw);
  for (const s of Array.isArray(parsed?.scores) ? parsed!.scores : []) {
    const idx = Number(s?.index);
    const sc = Number(s?.score);
    if (Number.isInteger(idx) && Number.isFinite(sc)) byIndex.set(idx, Math.max(0, Math.min(100, Math.round(sc))));
  }
  return byIndex;
}

/** Cross-model verification: run the whole panel in parallel, combine by
 *  consensus. A proposal passes only if the panel MEAN clears the bar and no
 *  single diverse judge vetoes it. Stored score is the mean. Judges that error
 *  or return junk simply abstain (they don't block); if none vote, fail closed. */
export async function verifyProposals(drafts: DraftProposal[]): Promise<VerifiedProposal[]> {
  if (drafts.length === 0) return [];
  const panelResults = await Promise.all(VERIFIER_PANEL.map((j) => runJudge(drafts, j)));

  return drafts.map((d, i) => {
    const verifierScores: VerifierScore[] = [];
    panelResults.forEach((res, k) => {
      const sc = res.get(i);
      if (sc !== undefined) verifierScores.push({ model: shortModel(VERIFIER_PANEL[k].model), score: sc });
    });
    const nums = verifierScores.map((v) => v.score);
    const mean = nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0;
    const passed = nums.length > 0 && mean >= PROPOSAL_SCORE_THRESHOLD && Math.min(...nums) >= PROPOSAL_VETO_FLOOR;
    return { ...d, score: Math.round(mean), passed, verifierScores };
  });
}
