// The self-improvement half of the frontier loop.
//
// Given a day's digest, draft concrete proposals for how FleetCrown itself
// should evolve, then put them through an adversarial self-critique gate before
// any reach a human. The loop AUTO-PROPOSES ONLY — a human accepts (→ a roadmap
// goal) or dismisses. Decision history grounds the next run so nothing is
// re-proposed.
//
// On model-agnosticism: proposals are generated by the GENERATOR model (Meta
// llama-3.3) and judged by a PANEL of different model lineages (verifyProposals).
// A single same-model judge shares the generator's blind spots — it certifies
// its own bad patterns. Judges from different training lineages have
// uncorrelated errors, so a proposal must convince every diverse judge that
// votes. That is what makes the judge strictly harder to fool than the
// generator — the whole point of the loop.

import { callGroqText } from "@/lib/groq";
import type { FrontierItem } from "./types";

// Short, stable grounding so proposals stay on-target for what FleetCrown is.
const FLEETCROWN_MISSION = `FleetCrown is a multi-user SaaS platform for commanding AI agent fleets across projects: builders register projects and launch/monitor/govern vendor-agnostic AI agents (claude, cursor, codex, gemini, grok) from one control plane. It is model-agnostic, self-hosted, and its north star is captain-mode: see and govern across the agents you've deployed. A local "Fleet Runner" desktop executes dispatches; the cloud orchestrates.`;

export type DraftProposal = { title: string; rationale: string; sourceUrls: string[] };

export type ProposalContext = {
  /** Titles of the owner's current active goals — do not duplicate. */
  activeGoalTitles: string[];
  /** Titles already proposed/considered (incl. dismissed) — do not repropose. */
  consideredTitles: string[];
  /** Open roadmap milestones ("Goal: milestone") — the declared gaps to fill. */
  openGaps: string[];
  /** Recently shipped, user-facing features — build on these, don't repropose. */
  recentlyShipped: string[];
};

// FleetCrown's real subsystems, so proposals target a concrete part of the
// product rather than generic "use AI" ideas. Stable enough to live here.
const FLEETCROWN_ARCHITECTURE = `FleetCrown's subsystems a proposal can target:
- Control plane: dispatch intents to agents, real-time SSE status, per-project cards, git-sync guard.
- Vendor-agnostic agents: adapter pattern over claude/cursor/codex/gemini/grok, AGENT_FALLBACK_ORDER, auto-reroute on capacity walls.
- Orchestration: orchestration_runs (open→close with inferred outcome), session.md handoffs, outcome capture.
- Fleet Runner (local desktop executor): owns PTYs, types into agent stdin, bridge SSE.
- Self-improvement: the frontier digest + this proposal loop + cross-model verifier.
- Life-OS surfaces: people, money, goals, habits, events, prompts library.
- Governance/captain-mode: see + govern across deployed agents (the north star).`;

function digestForPrompt(items: FrontierItem[]): string {
  return items.map((it, i) => `[${i}] (${it.category}) ${it.title} — ${it.summary} <${it.url}>`).join("\n");
}

const GENERATE_SYSTEM = `You are FleetCrown's self-improvement strategist.

${FLEETCROWN_MISSION}

${FLEETCROWN_ARCHITECTURE}

You will be given today's frontier developments, FleetCrown's RECENTLY SHIPPED features, its OPEN ROADMAP GAPS (planned-but-not-done milestones), and its current goals.

Your reasoning procedure (follow it):
1. Start from the OPEN ROADMAP GAPS and the subsystems above — that is what FleetCrown actually needs.
2. For each gap/subsystem, ask: does any of TODAY'S frontier developments offer a concrete technique, result, or tool that would advance it?
3. Propose ONLY where there is a real match. The proposal's subject is the GAP; the frontier development is the means. Title it after the FleetCrown change, not the paper.

Propose your best 1-3 gap-anchored matches. Each MUST:
- name a specific open gap or subsystem it advances, AND the specific frontier development it draws on;
- be concrete enough that an engineer could start building it this week;
- build ON recently-shipped work, never repropose it; not duplicate an active goal or a considered proposal.

Lean toward proposing when there is a plausible connection — a separate panel of reviewers will score and filter your proposals, so your job is to surface the strongest candidate matches, not to pre-reject them. Title each after the FleetCrown change, not the paper. Only return an empty list if today's developments have genuinely no plausible bearing on any gap or subsystem.

Return STRICT JSON only:
{"proposals":[{"title":"...","rationale":"... (2-3 sentences: name the frontier item, the FleetCrown subsystem/gap, and what concretely gets built)","sourceUrls":["<url from the candidate list>"]}]}`;

const CRITIQUE_SYSTEM = `You are an adversarial reviewer of self-improvement proposals for FleetCrown (a model-agnostic AI-agent-fleet control plane). Default to REJECTING. A proposal only earns a high score if it is ALL of: genuinely actionable, specific to FleetCrown (not generic AI hype), tied to a real frontier development, and NOT a restatement of an existing goal.

Score each proposal 0-100. Be harsh: vague, derivative, or me-too proposals score below 50. Only proposals a thoughtful founder would actually add to the roadmap score 70+.

Return STRICT JSON only: {"scores":[{"index":<number>,"score":<0-100>}]}`;

// Reasoning models (e.g. qwen3) emit a <think>…</think> preamble before the
// answer — drop it so the JSON after it parses, and so stray braces inside the
// reasoning don't get mistaken for the payload.
function stripReasoning(text: string): string {
  const idx = text.lastIndexOf("</think>");
  return idx === -1 ? text : text.slice(idx + "</think>".length);
}

// Pull the first balanced {...} object out of a (possibly fenced) model reply.
function extractJson(raw: string): string | null {
  const text = stripReasoning(raw);
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const body = fenced ? fenced[1] : text;
  const start = body.indexOf("{");
  if (start === -1) return null;
  let depth = 0;
  for (let i = start; i < body.length; i++) {
    if (body[i] === "{") depth++;
    else if (body[i] === "}" && --depth === 0) return body.slice(start, i + 1);
  }
  return null;
}

function safeParse<T>(text: string): T | null {
  const json = extractJson(text);
  if (!json) return null;
  try { return JSON.parse(json) as T; } catch { return null; }
}

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim();
}

// Word-overlap (Jaccard) — a cheap code-level dedup net beyond the LLM's own
// instruction not to duplicate.
function tooSimilar(a: string, b: string): boolean {
  const wa = new Set(norm(a).split(" ").filter((w) => w.length > 3));
  const wb = new Set(norm(b).split(" ").filter((w) => w.length > 3));
  if (wa.size === 0 || wb.size === 0) return false;
  let inter = 0;
  for (const w of wa) if (wb.has(w)) inter++;
  const union = wa.size + wb.size - inter;
  return inter / union >= 0.6;
}

/**
 * Why the generator produced nothing — because "nothing" has four causes with
 * four different fixes, and they were indistinguishable.
 *
 * The frontier loop surfaced no proposal between 2026-06-24 and 2026-08-25.
 * Two months, every night, and the only recoverable fact was `drafted: 0`.
 * A dead model, a reply that would not parse, a model that legitimately found
 * no match, and a dedup filter eating every draft all produced that same zero.
 * The first needs a repin, the second a prompt change, the third a rethink of
 * what the loop is fed, the fourth a looser filter — so collapsing them into
 * one number made the next step unknowable.
 */
export type GenerationOutcome =
  | "drafted"
  /** The model call threw (dead id, 429, timeout). `error` carries the message. */
  | "call-failed"
  /** A reply arrived but no JSON object could be extracted from it. */
  | "unparseable"
  /** Valid JSON, and the model deliberately returned an empty proposal list. */
  | "model-returned-empty"
  /** The model proposed, and every draft was dropped as a duplicate. */
  | "all-deduped"
  /** No digest items to reason about. */
  | "no-items";

export type GenerationResult = {
  drafts: DraftProposal[];
  outcome: GenerationOutcome;
  /** Present only for `call-failed`. */
  error?: string;
  /** How many the model returned before dedup — separates "proposed nothing"
   *  from "proposed, then we threw it all away". */
  returned: number;
  /**
   * Present only for `unparseable` — the head of the reply that would not
   * parse. Without it, "unparseable" is the same "which of several causes?"
   * question one level down: a refusal, a prose preamble, a fenced block we
   * mis-handle and a truncated object all fail to parse and each needs a
   * different fix. Truncated, because this is stored and read by a human.
   */
  rawSample?: string;
};

export async function generateProposals(
  items: FrontierItem[],
  ctx: ProposalContext,
): Promise<GenerationResult> {
  if (items.length === 0) return { drafts: [], outcome: "no-items", returned: 0 };
  const validUrls = new Set(items.map((it) => it.url));

  const user = [
    ctx.openGaps.length ? `OPEN ROADMAP GAPS — start here; these are what FleetCrown needs:\n- ${ctx.openGaps.join("\n- ")}` : "",
    `\nTODAY'S FRONTIER DEVELOPMENTS — match these against the gaps above:\n${digestForPrompt(items)}`,
    ctx.recentlyShipped.length ? `\nRECENTLY SHIPPED (build on, do NOT repropose):\n- ${ctx.recentlyShipped.join("\n- ")}` : "",
    ctx.activeGoalTitles.length ? `\nCurrent active goals (do NOT duplicate):\n- ${ctx.activeGoalTitles.join("\n- ")}` : "",
    ctx.consideredTitles.length ? `\nAlready considered (do NOT repropose):\n- ${ctx.consideredTitles.join("\n- ")}` : "",
  ].join("\n");

  let raw: string;
  try {
    raw = await callGroqText(user, { systemPrompt: GENERATE_SYSTEM, maxTokens: 1100, temperature: 0.4, timeoutMs: 22_000 });
  } catch (err) {
    // Was `catch { return [] }`. For the eight days the default Groq model
    // 404'd, that turned a hard outage into "the model had no ideas today".
    return {
      drafts: [], outcome: "call-failed", returned: 0,
      error: err instanceof Error ? err.message : String(err),
    };
  }

  const parsed = safeParse<{ proposals?: unknown }>(raw);
  if (!parsed) return { drafts: [], outcome: "unparseable", returned: 0, rawSample: raw.slice(0, 400) };
  const list = Array.isArray(parsed.proposals) ? parsed.proposals : [];
  const drafts: DraftProposal[] = [];
  for (const p of list) {
    if (typeof p !== "object" || !p) continue;
    const title = String((p as Record<string, unknown>).title ?? "").trim();
    const rationale = String((p as Record<string, unknown>).rationale ?? "").trim();
    const urlsRaw = (p as Record<string, unknown>).sourceUrls;
    const sourceUrls = Array.isArray(urlsRaw) ? urlsRaw.map(String).filter((u) => validUrls.has(u)) : [];
    if (!title || !rationale) continue;
    // Code-level dedup against goals + already-considered + earlier drafts this run.
    if ([...ctx.activeGoalTitles, ...ctx.consideredTitles, ...drafts.map((d) => d.title)].some((t) => tooSimilar(t, title))) continue;
    drafts.push({ title, rationale, sourceUrls });
    if (drafts.length >= 3) break;
  }
  // `returned` vs `drafts.length` is the whole point of separating these two:
  // "the model proposed nothing" and "the model proposed and we discarded all
  // of it as duplicates" are different problems wearing the same zero.
  const outcome: GenerationOutcome =
    drafts.length > 0 ? "drafted"
      : list.length > 0 ? "all-deduped"
        : "model-returned-empty";
  return { drafts, outcome, returned: list.length };
}

// The judge panel — model lineages DIFFERENT from the generator (Meta llama-3.3)
// so their errors are uncorrelated with it and each other. Reasoning models get
// token headroom for their <think> preamble (stripped before parsing).
export type Judge = { model: string; maxTokens: number };
export const VERIFIER_PANEL: Judge[] = [
  { model: "openai/gpt-oss-120b", maxTokens: 600 },  // OpenAI lineage
  { model: "qwen/qwen3.6-27b",    maxTokens: 3500 }, // Qwen / Alibaba lineage (reasoning — needs room for <think>)
];

/** A proposal surfaces only if the panel's MEAN score clears this bar… */
export const PROPOSAL_SCORE_THRESHOLD = 70;
/** …AND no single judge scores below this (one diverse judge can veto, so a
 *  proposal one lineage loves and another hates never slips through). */
export const PROPOSAL_VETO_FLOOR = 50;

export type VerifierScore = { model: string; score: number };
export type VerifiedProposal = DraftProposal & {
  score: number;               // consensus = lowest panel score (conservative)
  passed: boolean;             // every voting judge >= threshold (>=1 voter)
  verifierScores: VerifierScore[];
};

function shortModel(id: string): string {
  return id.includes("/") ? id.split("/")[1] : id;
}

/** A judge's verdict, plus WHY it said nothing when it said nothing. */
export type JudgeRun = { scores: Map<number, number>; error?: string };

// One judge scores every draft in a single call → Map<draftIndex, score>.
// A judge that errors or returns junk abstains rather than blocking — but the
// abstention now carries its reason. Silent abstention is how a total panel
// outage came to look exactly like "the panel rejected everything": both end
// with zero surfaced proposals and, before this, zero explanation. The reason
// matters because the responses are opposite — repin or retry a broken judge,
// rethink the proposals a working one rejected.
async function runJudge(drafts: DraftProposal[], judge: Judge): Promise<JudgeRun> {
  const user = `Proposals to review:\n${drafts.map((d, i) => `[${i}] ${d.title} — ${d.rationale}`).join("\n")}`;
  const byIndex = new Map<number, number>();
  let raw: string;
  try {
    raw = await callGroqText(user, {
      systemPrompt: CRITIQUE_SYSTEM,
      maxTokens: judge.maxTokens,
      temperature: 0.1,
      timeoutMs: 35_000, // reasoning judges (qwen <think>) need headroom
      model: judge.model,
      // NO fallback, deliberately. This panel's entire value is that its judges
      // come from different training lineages, so their errors are uncorrelated.
      // If a dead judge silently fell through to the other judge's model, two
      // "independent" votes would become one voter counted twice — while
      // `verifierScores` still reported two distinct names, and the veto floor
      // (one lineage can veto what another loves) would quietly stop existing.
      // An abstaining judge is honest and already handled: it surfaces in
      // judgeFailures, and a fully abstaining panel sets panelUnreachable.
      fallback: false,
    });
  } catch (err) {
    return { scores: byIndex, error: err instanceof Error ? err.message : String(err) };
  }
  const parsed = safeParse<{ scores?: Array<{ index?: unknown; score?: unknown }> }>(raw);
  for (const s of Array.isArray(parsed?.scores) ? parsed!.scores : []) {
    const idx = Number(s?.index);
    const sc = Number(s?.score);
    if (Number.isInteger(idx) && Number.isFinite(sc)) byIndex.set(idx, Math.max(0, Math.min(100, Math.round(sc))));
  }
  // Junk that parsed to no scores is an abstention with no exception to report.
  return { scores: byIndex };
}

/** A judge that could not vote, and why. */
export type JudgeFailure = { model: string; error: string };

export type VerificationResult = {
  verified: VerifiedProposal[];
  /** Empty when every judge voted. Non-empty means the panel was DEGRADED —
   *  a rejection reached on fewer votes than the design assumes. */
  judgeFailures: JudgeFailure[];
  /** True when NOT ONE judge voted. Everything fails closed, correctly, but
   *  for a reason that has nothing to do with proposal quality — the case that
   *  must never again be mistaken for "the panel rejected them". */
  panelUnreachable: boolean;
};

/** Cross-model verification: run the whole panel in parallel, combine by
 *  consensus. A proposal passes only if the panel MEAN clears the bar and no
 *  single diverse judge vetoes it. Stored score is the mean. Judges that error
 *  or return junk simply abstain (they don't block); if none vote, fail closed
 *  — and say so, via `panelUnreachable`, rather than reporting a verdict the
 *  panel never actually reached. */
export async function verifyProposals(drafts: DraftProposal[]): Promise<VerificationResult> {
  if (drafts.length === 0) return { verified: [], judgeFailures: [], panelUnreachable: false };
  const panelResults = await Promise.all(VERIFIER_PANEL.map((j) => runJudge(drafts, j)));

  const judgeFailures: JudgeFailure[] = panelResults.flatMap((res, k) =>
    res.error ? [{ model: shortModel(VERIFIER_PANEL[k].model), error: res.error }] : []);
  const anyVoted = panelResults.some((res) => res.scores.size > 0);

  const verified = drafts.map((d, i) => {
    const verifierScores: VerifierScore[] = [];
    panelResults.forEach((res, k) => {
      const sc = res.scores.get(i);
      if (sc !== undefined) verifierScores.push({ model: shortModel(VERIFIER_PANEL[k].model), score: sc });
    });
    const nums = verifierScores.map((v) => v.score);
    const mean = nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0;
    const passed = nums.length > 0 && mean >= PROPOSAL_SCORE_THRESHOLD && Math.min(...nums) >= PROPOSAL_VETO_FLOOR;
    return { ...d, score: Math.round(mean), passed, verifierScores };
  });

  return { verified, judgeFailures, panelUnreachable: !anyVoted };
}
