import { NextResponse } from "next/server";
import { readFileSync } from "fs";
import { PROMPTS_FILE } from "@/lib/agent-config";
import { getSessionUserId } from "@/lib/session";
import { PROMPT_TEMPLATES } from "@/config/prompt-library";

// readFileSync has no Next.js dynamic signal — force dynamic so middleware runs.
export const dynamic = "force-dynamic";

export type AgentPrompt = {
  key: string;
  slot: number | null;
  icon: string;
  label: string;
  style: "primary" | "action" | "more" | "dimension" | "internal" | "danger";
  category: string;
  dimensionId: string | null;
  prompt: string;
  /** True when the consumer should fire the prompt immediately on click;
   *  false (default) means click should fill the composer textarea so the
   *  user can preview/edit before sending. Per the unified UX shipped
   *  2026-05-31; before that, every entry point made its own per-component
   *  decision and same prompt could send-or-fill depending on the surface. */
  sendNow?: boolean;
};

/** Merges the legacy JSON prompt file with the TS PROMPT_TEMPLATES library
 *  into the AgentPrompt shape consumed by DimensionSection. TS entries that
 *  set `agentKey` win on conflict — letting the TS file gradually replace
 *  the JSON without breaking the daemon, which still reads from JSON.
 *  Once all daemon consumers migrate to this API, the JSON file becomes
 *  pure build artifact (generated by scripts/generate-agent-prompts.ts). */
function mergePromptSources(): AgentPrompt[] {
  let jsonPrompts: AgentPrompt[] = [];
  try {
    const raw = readFileSync(PROMPTS_FILE(), "utf-8");
    jsonPrompts = JSON.parse(raw);
  } catch {
    // JSON file missing is fine — TS source is the SSOT
  }

  // TS templates with agentKey set become AgentPrompt entries.
  const tsPrompts: AgentPrompt[] = PROMPT_TEMPLATES
    .filter((t) => t.agentKey)
    .map((t) => ({
      key:         t.agentKey!,
      slot:        t.slot ?? null,
      icon:        t.icon ?? "•",
      label:       t.name,
      style:       (t.style ?? "dimension") as AgentPrompt["style"],
      category:    t.category,
      dimensionId: t.dimensionId ?? null,
      prompt:      t.template,
      sendNow:     t.sendNow ?? false,
    }));

  // TS wins on key conflict — this is how the SSOT migration happens
  // incrementally without breaking the daemon's JSON consumers.
  const byKey = new Map<string, AgentPrompt>();
  for (const p of jsonPrompts) byKey.set(p.key, p);
  for (const p of tsPrompts) byKey.set(p.key, p);
  return [...byKey.values()];
}

export async function GET() {
  const userId = await getSessionUserId();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  return NextResponse.json(mergePromptSources());
}
