#!/usr/bin/env bash
# Build <repo>/<app_dir>/.env.selfhost.local for an app from its Vercel env
# (fresh `vercel env pull` if the repo is linked, else ~/dev/vercel-env-backup).
# Sanitizes Vercel-isms, rewrites DB URL to the box-local Postgres, points
# auth/site URLs at the new domain, adds AUTH_TRUST_HOST for proxied Auth.js.
# Usage: gen-env.sh <app>
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
app_lookup "${1:?usage: gen-env.sh <app>}"

SRC_DIR="$REPO/$APP_DIR"
OUT="$SRC_DIR/.env.selfhost.local"
DOMAIN="${DOMAINS%%,*}"

# Source env: fresh pull beats stale backup
RAW=$(mktemp); trap 'rm -f "$RAW"' EXIT
if [ -d "$REPO/.vercel" ] || vercel link --yes --project "$NAME" --scope orangecat --cwd "$REPO" >/dev/null 2>&1; then
  vercel env pull "$RAW" --environment=production --yes --cwd "$REPO" >/dev/null 2>&1 || true
fi
if [ ! -s "$RAW" ]; then
  BACKUP="$HOME/dev/vercel-env-backup/$NAME.env"
  [ -f "$BACKUP" ] && cp "$BACKUP" "$RAW"
fi
[ -s "$RAW" ] || { echo "WARN: no Vercel env found for $NAME — writing minimal env"; : > "$RAW"; }

DB_URL=""
if [ "$DB" != "-" ]; then
  pass=$(box "grep '^$DB|' ~/.db-credentials | cut -d'|' -f2")
  [ -z "$pass" ] && { echo "ERROR: no credentials for db $DB on box"; exit 1; }
  DB_URL="postgresql://$DB:$pass@localhost:5432/$DB"
fi

{
  echo "# Generated by gen-env.sh $(date +%F) — runtime env for $DOMAIN"
  while IFS= read -r line; do
    case "$line" in \#*|"") continue;; esac
    key="${line%%=*}"
    val="${line#*=}"
    val="${val%\"}"; val="${val#\"}"; val="${val%\\n}"   # strip quotes + literal trailing \n
    case "$key" in
      VERCEL|VERCEL_*|NX_DAEMON|TURBO_*) continue ;;
      DATABASE_URL|DIRECT_URL|POSTGRES_URL|POSTGRES_PRISMA_URL|POSTGRES_URL_NON_POOLING)
        [ -n "$DB_URL" ] && val="$DB_URL" ;;
      NEXTAUTH_URL|AUTH_URL|NEXT_PUBLIC_APP_URL|NEXT_PUBLIC_BASE_URL|NEXT_PUBLIC_SITE_URL)
        val="https://$DOMAIN" ;;
    esac
    printf '%s="%s"\n' "$key" "${val//\"/\\\"}"
  done < "$RAW"
  [ -n "$DB_URL" ] && grep -qE '^(DATABASE_URL)=' "$RAW" || { [ -n "$DB_URL" ] && echo "DATABASE_URL=$DB_URL"; }
  echo "AUTH_TRUST_HOST=true"
} > "$OUT"
chmod 600 "$OUT"
echo "wrote $OUT ($(grep -c '=' "$OUT") vars, db=$DB)"
