#!/usr/bin/env bash
# Generate + push systemd units, launch scripts, and Caddy vhosts for every
# app in apps.conf. Idempotent. Does NOT touch the four pre-existing services
# (bridge, fleetcrown, orangecat, revampit) or any /opt/<app>/.env.
# Usage: sync-infra.sh [app ...]   (no args = all)
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

apps=("$@")
[ ${#apps[@]} -eq 0 ] && mapfile -t apps < <(app_names)

# One-time: Caddy import dir + import line
box 'sudo mkdir -p /etc/caddy/apps.d
grep -q "import apps.d" /etc/caddy/Caddyfile || \
  echo "import apps.d/*.caddy" | sudo tee -a /etc/caddy/Caddyfile >/dev/null'

for app in "${apps[@]}"; do
  app_lookup "$app"
  echo "=== sync $NAME (port $PORT) ==="

  launch=$(cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
HERE="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
if [ -f "\$HERE/.env" ]; then set -a; source "\$HERE/.env"; set +a; fi
export NODE_ENV=production PORT=$PORT HOSTNAME=127.0.0.1
SERVER_JS=\$(find "\$HERE" -maxdepth 4 -name server.js -not -path "*node_modules*" | head -1)
if [ -n "\$SERVER_JS" ]; then exec /usr/bin/node "\$SERVER_JS"; fi
# Non-Next services define their own entrypoint via START_CMD in .env
exec bash -c "\${START_CMD:?no server.js found and START_CMD unset}"
EOF
)

  unit=$(cat <<EOF
[Unit]
Description=$NAME application server (self-hosted, generated by sync-infra.sh)
After=network-online.target postgresql.service
Wants=network-online.target
# Never enter the start-limit "failed" lockout: a crash-looping app should keep
# retrying (Restart=on-failure) instead of staying down until a manual
# `systemctl reset-failed`.
StartLimitIntervalSec=0

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/opt/$NAME/app
ExecStart=/opt/$NAME/app/launch.sh
Restart=on-failure
RestartSec=3
# Bound the stop phase so a `systemctl restart` can't block on a slow-draining
# Next process (default 90s). KillMode=mixed SIGTERMs the main proc then SIGKILLs
# the cgroup, freeing the port fast for the new process.
TimeoutStopSec=15
KillMode=mixed
# Memory ceiling: a leaking/runaway Next process is OOM-killed (and restarted)
# alone instead of taking the whole small box down. MemoryHigh throttles first.
MemoryMax=1G
MemoryHigh=768M
StandardOutput=journal
StandardError=journal
# Any failure fires an instant Telegram (see install-host-alerts.sh). Wired here
# so a newly-synced app is alertable from its first boot, not only after a
# separate install-host-alerts run.
OnFailure=notify-failure@%n.service

[Install]
WantedBy=multi-user.target
EOF
)

  box "sudo mkdir -p /opt/$NAME/app && sudo chown -R ubuntu:ubuntu /opt/$NAME
cat > /opt/$NAME/app/launch.sh <<'LAUNCH_EOF'
$launch
LAUNCH_EOF
chmod +x /opt/$NAME/app/launch.sh
sudo tee /etc/systemd/system/$NAME-app.service >/dev/null <<'UNIT_EOF'
$unit
UNIT_EOF
sudo systemctl daemon-reload && sudo systemctl enable $NAME-app >/dev/null 2>&1"

  if [ "$DOMAINS" != "-" ]; then
    caddy_domains="${DOMAINS//,/, }"
    vhost=$(cat <<EOF
$caddy_domains {
  encode zstd gzip
  handle_path /uploads/* {
    root * /opt/$NAME/uploads
    file_server
  }
  reverse_proxy 127.0.0.1:$PORT {
    flush_interval -1
  }
}
EOF
)
    box "sudo tee /etc/caddy/apps.d/$NAME.caddy >/dev/null <<'CADDY_EOF'
$vhost
CADDY_EOF
sudo mkdir -p /opt/$NAME/uploads && sudo chown ubuntu:ubuntu /opt/$NAME/uploads"
  fi
done

box 'sudo caddy validate --config /etc/caddy/Caddyfile >/dev/null && sudo systemctl reload caddy && echo "caddy reloaded OK"'
