import assert from "node:assert/strict";
import {
  cleanDescription,
  isPublicTestArtifact,
  publicHeroNote,
  summarizeDescription,
} from "../../src/lib/project-display";

assert.equal(cleanDescription("Local repository imported from fleetcrown-ui"), null);
assert.equal(cleanDescription("A weatherproof box for valuables."), "A weatherproof box for valuables.");

assert.equal(isPublicTestArtifact("smoke-1783188931860-gh"), true);
assert.equal(isPublicTestArtifact("orangecat"), false);

const dumpAfterPitch =
  "Life OS + AI agent fleet command center. MUTUAL DOGFOOD WITH ORANGECAT: KNOWN BUG — v1 entity-create from bearer-token callers hits RLS 42501.";
const pitch = publicHeroNote(dumpAfterPitch);
assert.ok(pitch);
assert.ok(!/known bug|mutual dogfood|42501/i.test(pitch), pitch);

const dumpFirst =
  "KNOWN BUG — v1 entity-create hits RLS 42501 and the ORANGECAT_WEBHOOK_SECRET is unset.";
assert.equal(publicHeroNote(dumpFirst), null, "a dump that starts as a dump stays hidden");

const short = "HamsterCheek is a weatherproof box for valuables.";
assert.equal(publicHeroNote(short), short);

const essay =
  "Prime tower is a project generated by FleetCrown, a command center for AI agent fleets, using Next.js, Tailwind CSS, and TypeScript. Extra sentences should not reach the hero.";
const summarized = publicHeroNote(essay);
assert.ok(summarized);
assert.ok(summarized!.length <= 80, summarized);
assert.equal(summarized, summarizeDescription(essay, 72));

console.log("✓ project-display tests passed");
