// Solon signing + webhook verification — the cross-repo contracts.
//
// The signing vector was generated by Solon's own signMessage() (fixed key
// 0x11…11, UUID session). RFC6979 signing is deterministic, so the signature
// bytes must match EXACTLY — any drift in magic/varint/digest/header breaks
// this test instead of breaking Loki's votes in prod. Pure: no DB, no network.
import assert from "node:assert";
import {
  addressFromPrivateKey,
  signBitcoinMessage,
  solonVoteMessage,
} from "../../src/lib/integrations/solon-message";
import { verifySolonWebhookSignature } from "../../src/lib/integrations/solon-webhook";
import { createHmac } from "node:crypto";

const PRIV = "1111111111111111111111111111111111111111111111111111111111111111";
const ADDRESS = "1Q1pE5vPGEEMqRcVRMbtBK842Y6Pzo6nK9";
const SESSION = "11111111-2222-4333-8444-555555555555";
const MESSAGE = `Solon vote\nsession:${SESSION}\nchoice:yes\nvoter:${ADDRESS}`;
const SIGNATURE = "IPTWOIU6N/j674TVg2T2ej7uRDi5AkcGVRtfY9CC04ezFV6g6um12yrjJ5W8silm95MnfPeVFjIz0HYtd6Aises=";

// Address derivation matches Solon's.
assert.strictEqual(addressFromPrivateKey(PRIV), ADDRESS, "address derivation drifted from Solon");

// Canonical message is byte-identical to Solon's voteMessage().
assert.strictEqual(
  solonVoteMessage({ sessionId: SESSION, choice: "yes", memberAddress: ADDRESS }),
  MESSAGE,
  "canonical vote message drifted from Solon",
);

// Deterministic signature matches Solon's signer byte-for-byte.
assert.strictEqual(signBitcoinMessage(MESSAGE, PRIV), SIGNATURE, "signature drifted from Solon's signer");

// Webhook HMAC verification: accepts the correctly signed body, both header forms.
const secret = "test-secret";
const body = '{"event":"decision.finalized","decision_id":"x"}';
const hex = createHmac("sha256", secret).update(body).digest("hex");
assert.ok(verifySolonWebhookSignature(body, `sha256=${hex}`, secret), "sha256= form rejected");
assert.ok(verifySolonWebhookSignature(body, hex, secret), "bare hex form rejected");
assert.ok(!verifySolonWebhookSignature(body, `sha256=${"0".repeat(64)}`, secret), "forged accepted");
assert.ok(!verifySolonWebhookSignature(`${body} `, `sha256=${hex}`, secret), "tampered body accepted");
assert.ok(!verifySolonWebhookSignature(body, null, secret), "missing header accepted");

// Webhook receivers authenticate via HMAC, not a session — the auth middleware
// matcher MUST exclude them, or NextAuth 401s the POST before the route runs.
// This exact omission shipped once (Solon doorbell unreachable in prod until a
// signed replay caught it): pin every self-authenticating receiver here.
import { readFileSync } from "node:fs";
import { join } from "node:path";
const proxySource = readFileSync(join(__dirname, "../../src/proxy.ts"), "utf8");
const matcherExclusion = proxySource.match(/"\/\(\(\?!(.+)\)\.\+\)"/)?.[1];
assert.ok(matcherExclusion, "proxy.ts matcher exclusion pattern not found");
for (const receiver of ["api/orangecat/", "api/solon/", "api/stripe/webhook"]) {
  assert.ok(
    matcherExclusion.split("|").includes(receiver.replace(/\./g, "\\.")) ||
      matcherExclusion.split("|").includes(receiver),
    `auth middleware must exclude ${receiver} (HMAC-authenticated receiver)`,
  );
}

console.log("solon-message: signing vector + webhook verification + middleware exclusion OK");
